### ISSUE TITLE
Taro中产生大量内联样式

### ISSUE THREAD

**Issue by idootop** [motere/fower#27]
写起来是爽了，但是如何优化代码体积那？
能否通过原子类className组合+内联样式的方式来优化代码体积？
能否像taillwind那样可以purge未用到的原子类，进一步精简代码？
这是目前在我们项目中使用fower的几个痛点，还请指教。

**Comment by xdoer** [comment]
@idootop fower 在类 React 框架中是运行时库，tailwind 是编译时的。在 Taro 中，class 样式必须写到 css 文件中，而运行时是没有办法调用 fs  API 往 css 文件中添加内容，所以在 Taro 中只能采用内联的方式。
同样也是由于是运行时的缘故，也没有办法实现 “purge 未用到的原子类”。

fower 体积其实并不大。项目代码体积大，可以考虑分包，压缩代码，图片用 CDN 链接等手段去优化。

**Comment by idootop** [comment]
嗯嗯，是我理解错了。
吃午饭的时候还在想这件事，想通了过来关issue，发现你已经回复了，好快～
非常感谢，fower 和 stook 非常棒的两个库，希望能一直维护下去，越做越好！

**Comment by tourze** [comment]
> @idootop fower 在类 React 框架中是运行时库，tailwind 是编译时的。在 Taro 中，class 样式必须写到 css 文件中，而运行时是没有办法调用 fs API 往 css 文件中添加内容，所以在 Taro 中只能采用内联的方式。
> 同样也是由于是运行时的缘故，也没有办法实现 “purge 未用到的原子类”。

有个疑惑，这种运行时的实现方式，性能损耗会大吗？

**Comment by xdoer** [comment]
@tourze 具体纸面上的数据没测过，但性能损耗并不大。 

fower 中有对每个 prop 进行缓存。缓存后，当在任意组件上遍历到该 prop 时，都是直接从缓存取值。只有没命中缓存的，才会遍历 n 多个插件，计算样式，插入样式，这个过程可能有一些性能损耗。

实际开发过程中，你会发现其实常用的样式 prop 就那几个，所以整体来看性能损耗并不大。

我们已经有成熟的使用 fower 的小程序产品《剧本杀展会》部署到了线上，你可以看一下。
